# Generated by Django 4.0.8 on 2023-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_App', '0002_applyjob_joblisting_applyjob_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='file',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='coverletter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
