# Generated by Django 4.0.8 on 2023-06-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_App', '0005_maximum_experience_minimum_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='experience',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='maximum_exp',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recruitment_App.maximum_experience'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='minimum_exp',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recruitment_App.minimum_experience'),
        ),
    ]
