# Generated by Django 4.0.8 on 2023-06-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_App', '0006_remove_joblisting_experience_joblisting_maximum_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
